#pragma once

#ifndef MINIACID_AUTOMATION_MAX_NODES
#define MINIACID_AUTOMATION_MAX_NODES 36
#endif

#ifndef MINIACID_AUTOMATION_POOL_NODES
// Total automation nodes available across all lanes.
// This is a shared pool to avoid storing large arrays in every pattern.
#define MINIACID_AUTOMATION_POOL_NODES 256
#endif

#ifndef MINIACID_DISABLE_AUTOMATION_APPLY
#define MINIACID_DISABLE_AUTOMATION_APPLY 0
#endif

#ifndef MINIACID_AUTOMATION_SAMPLE_STRIDE
// Update automation every N samples to reduce CPU load.
// #define MINIACID_AUTOMATION_SAMPLE_STRIDE 8
// #define MINIACID_AUTOMATION_SAMPLE_STRIDE 16
// #define MINIACID_AUTOMATION_SAMPLE_STRIDE 32
#define MINIACID_AUTOMATION_SAMPLE_STRIDE 255
#endif

#if MINIACID_AUTOMATION_SAMPLE_STRIDE < 1
#undef MINIACID_AUTOMATION_SAMPLE_STRIDE
#define MINIACID_AUTOMATION_SAMPLE_STRIDE 1
#endif

#ifndef MINIACID_DISABLE_FOCUS_PRINTF
#define MINIACID_DISABLE_FOCUS_PRINTF 0
#endif

#ifndef MINIACID_PERF_TEST_DISABLE_DRUM_FX
#define MINIACID_PERF_TEST_DISABLE_DRUM_FX 0
#endif

#ifndef MINIACID_PERF_TEST_DISABLE_DRUM_AUTOMATION
#define MINIACID_PERF_TEST_DISABLE_DRUM_AUTOMATION 0
#endif

#ifndef MINIACID_PERF_TEST_DISABLE_DRUM_ENGINE_AUTOMATION
#define MINIACID_PERF_TEST_DISABLE_DRUM_ENGINE_AUTOMATION 0
#endif

#ifndef MINIACID_PERF_TEST_DISABLE_KNOB_DRAW
#define MINIACID_PERF_TEST_DISABLE_KNOB_DRAW 0
#endif

#ifndef MINIACID_UI_MIN_FRAME_MS
#if defined(ARDUINO)
#define MINIACID_UI_MIN_FRAME_MS 40
#else
#define MINIACID_UI_MIN_FRAME_MS 0
#endif
#endif

#ifndef MINIACID_KNOB_LUT_STEPS
#define MINIACID_KNOB_LUT_STEPS 64
#endif

#ifndef MINIACID_DISABLE_KNOB_FACE_CACHE
#if defined(ARDUINO)
#define MINIACID_DISABLE_KNOB_FACE_CACHE 1
#else
#define MINIACID_DISABLE_KNOB_FACE_CACHE 0
#endif
#endif

#ifndef MINIACID_SCENE_MAX_BYTES
#if defined(ARDUINO)
// #define MINIACID_SCENE_MAX_BYTES 16384
#define MINIACID_SCENE_MAX_BYTES 85880
#else
#define MINIACID_SCENE_MAX_BYTES 0
#endif
#endif

#ifndef MINIACID_SCENE_DEBUG
#if defined(ARDUINO)
#define MINIACID_SCENE_DEBUG 0
#else
#define MINIACID_SCENE_DEBUG 1
#endif
#endif
